### ISSUE TITLE
The formulations of paper 

### ISSUE THREAD

**Issue by WangzcBruce** [Adamdad/KnowledgeFactor#1]
Excuse, a question about the derivations of the Variational Bound for Mutual Information is not in the supplementary materials .

**Comment by Adamdad** [comment]
Thanks for the question. I will modify the arxiv version to include the supplementary material. I also upload a version in the google drive for your fast reference (https://drive.google.com/file/d/12CyoMWD_2cYH95_QdcmbPOeN2Ejkt8-F/view?usp=sharing).
