### ISSUE TITLE
A question occurs when load pretrained wideresnet as teacher 

### ISSUE THREAD

**Issue by huang-hz** [Adamdad/KnowledgeFactor#4]
Nice work! But a problem occur when i test running :
Pretrained ResNet18 load successfully in the fold configs/Imagenet-kf ,while it shows "Teacher model not loaded “ when I test running with configs/imagenet-kf/wideresnet28-2*.py. Then I catch the exception , following is some of the error.

RuntimeError ('Error(s) in loading state_dict for ModuleDict:\n\tsize mismatch for backbone.layer1.0.conv1.weight: copying a param with shape torch.Size([160, 16, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 16, 3, 3]).\n\tsize mismatch for backbone.layer1.0.conv2.weight: copying a param with shape torch.Size([160, 160, 3, 3]) from checkpoint, the shape in current model is torch.Size([32, 32, 3, 3]).\n\tsize mismatch for backbone.layer1.0.bn2.weight: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([32]).\n\tsize mismatch for backbone.layer1.0.bn2.bias: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([32]).\n\tsize mismatch for backbone.layer1.0.bn2.running_mean: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([32]).\n\tsize mismatch for backbone.layer1.0.bn2.running_var: copying a param with shape torch.Size([160]) from checkpoint, the shape in current model is torch.Size([32]).\n\tsize mismatch for backbone.layer1.0.downsample.0.weight: copying a param with shape torch.Size([160, 16, 1, 1]) from checkpoint, the shape in current model is torch.Size([32, 16, 1, 1]).

**Comment by Adamdad** [comment]
Sorry but I did not get where you are. I do not have wideresnet28-2*.py file under the configs/imagenet-kf/ folder. So could you please specify which config you are using?

**Comment by huang-hz** [comment]
Sorry for missusing asterisk. Actually  i want to express the meaning of all the files end with ".py" and start with "wideresnet28-2". For more details, error message above comes from the running with config named "wideresnet28-2_mobilenetv2_b128x1_cifar10_softtar_kf.py".

**Comment by Adamdad** [comment]
Dear Huang-hz, to check if my code is able to load the correct teacher weights, I just run the code myself again. I download the checkpoint for wideresnet-28-2 teacher [weights](https://drive.google.com/file/d/1_MgpoL8F_2wwgC6UD_tdDcX_teGgg3Mh/view?usp=sharing) and write the teacher path in the config. I can correctly load the weights (As shown in the Figure below). Please make sure you download the `correct ckp that matches the model config`. For example, for you can not load the weights for the WideResNet-28-10 into a WideResNet-28-2 model.

    # model settings
    model = dict(
        type='KFImageClassifier',
        kd_loss=dict(type='SoftTarget',
                     temperature=10.0),
        train_cfg=dict(
            lambda_kd=0.1,
            lambda_feat=1.0,
            alpha=1.0,
            beta=1e-3,
            task_weight=1.0,
            teacher_checkpoint='epoch_200.pth', # Input your teacher checkpoint
            feat_channels=dict(student=[128, 256, 512],
                               teacher=[32, 64, 128]),
        ),
        backbone=dict(
            num_task=1,
            student=dict(
                CKN=dict(type='ResNet_CIFAR',
                         depth=18,
                         num_stages=4,
                         out_indices=(1, 2, 3),
                         style='pytorch'),
                TSN=dict(type='TSN_backbone',
                         backbone=dict(type='MobileNetV2_CIFAR',
                                       out_indices=(7, ),
                                       widen_factor=0.5),
                         in_channels=1280,
                         out_channels=512)
            ),
            teacher=dict(
                type='WideResNet_CIFAR',
                depth=28,
                stem_channels=16,
                base_channels=16 * 2,
                num_stages=3,
                strides=(1, 2, 2),
                dilations=(1, 1, 1),
                out_indices=(0, 1, 2),
                out_channel=128,
                style='pytorch')
        ),
        neck=dict(
            student=dict(type='GlobalAveragePooling'),
            teacher=dict(type='GlobalAveragePooling')
        ),
        head=dict(
            student=dict(
                type='LinearClsHead',
                num_classes=10,
                in_channels=512,
                loss=dict(
                    type='LabelSmoothLoss',
                    label_smooth_val=0.1,
                    num_classes=10,
                    reduction='mean',
                    loss_weight=1.0),
            ),
            task=dict(
                type='LinearClsHead',
                num_classes=10,
                in_channels=512,
                loss=dict(
                    type='LabelSmoothLoss',
                    label_smooth_val=0.1,
                    num_classes=10,
                    reduction='mean',
                    loss_weight=1.0),
            ),
            teacher=dict(
                type='LinearClsHead',
                num_classes=10,
                in_channels=128,
                loss=dict(type='CrossEntropyLoss',
                          loss_weight=1.0),
            )
        )
    )

![image](https://user-images.githubusercontent.com/26020510/190398777-aabf8ece-d905-4e73-836a-bcc569523207.png)

**Comment by huang-hz** [comment]
Oh,my bad!!!! It is totally my fault to have WideResNet-28-10 and WideResNet-28-2 mixed up. I downloaded the weights for the WideResNet-28-2 again and load it correctly. Thank you for your kind reply and pointing out the problem.

Besides, I am working on some extension work based on this excellent KnowledgeFactor work. Hope you don't mind if I come to the Issues for your help sometimes.

**Comment by Adamdad** [comment]
No problem. Questions are welcome at any time.

**Comment by huang-hz** [comment]
Hi, have you met such a problem “TypeError: 'MMDistributedDataParallel' object is not subscriptable" . It let me have to train the code with only one GPU.

![image](https://user-images.githubusercontent.com/35068458/198823631-b0c078d7-069b-46a6-babd-ef60900a1e63.png)

while my student structure is similar to yours 

![image](https://user-images.githubusercontent.com/35068458/198823794-ff211bd4-5fa5-4f7f-b16f-ace7433757df.png)

**Comment by Adamdad** [comment]
The student should be a nn.ModuleDict, rather than a MMDistributedDataParallel. How did you initialise the model?

**Comment by huang-hz** [comment]
> initialise

I initialize the student in a similar way 

![image](https://user-images.githubusercontent.com/35068458/198823950-50b65115-1852-4be1-9756-4204828bb76a.png)

**Comment by Adamdad** [comment]
From my understanding, only the full model is a wrapped with a ` MMDistributedDataParallel`, while all modules inside should be a typical `torch.Module`. I am not sure why in your case, the inner module are also wrapped.

**Comment by huang-hz** [comment]
Congratulations!

I just see a new network modularisation work published on NIPS22, and the first author is familiar to me~
